defaults: &defaults
  twitter_api_key: MZNApF2jR4DL5oePdVlg
  twitter_api_secret: 8yUe0ggZQ2TTjInnzPbhoypU3AeKnazhXahATcYYs
  app_host: geeksurvey.com

development:
  <<: *defaults
  app_host: 'localhost:3000'

test:
  <<: *defaults

production:
  <<: *defaults